/-
VeriTile.Meta.TrustReport — GENERATED, do not edit by hand.

Regenerate with:  python3 scripts/gen_trust_report.py

Runs `#axiomsClean` on every `proven` LIBRARY theorem in
scripts/kernel-manifest.tsv. Elaborating this module is the whole-library
trust gate:

    lake env lean VeriTile/Meta/TrustReport.lean   -- exit 0 <=> all clean

A failure means a `proven` theorem's transitive proof depends on `sorryAx`
or a non-standard axiom (footprint outside {propext, Classical.choice,
Quot.sound}) — a real soundness finding, NOT something to paper over.

Coverage: 134 library theorems across 17 modules.
Standalone bench ports + bench/examples are audited by bench/audit_trust.sh.
-/
import VeriTile.Meta.StatementAudit
import VeriTile.Examples.ApproxGeLU
import VeriTile.Examples.FlashAttention1.Backward
import VeriTile.Examples.FlashAttention1.Backward.Math
import VeriTile.Examples.FlashAttention1.Core
import VeriTile.Examples.FlashAttention1.NaiveRefinement
import VeriTile.Examples.FlashAttention1.ScoreVariants.Backward
import VeriTile.Examples.FlashAttention1.ScoreVariants.Math
import VeriTile.Examples.FlashAttention2
import VeriTile.Triton.Launch.Blocked1D
import VeriTile.Triton.Launch.Blocked1DConfig
import VeriTile.Triton.Launch.Blocked1DFlat
import VeriTile.Triton.Launch.Blocked1DWrapper
import VeriTile.Triton.Launch.Line3
import VeriTile.Triton.Launch.Relational
import VeriTile.Triton.Launch.Serial
import VeriTile.Triton.Launch.StridedUnary
import VeriTile.Triton.Launch.StridedUnaryFlat

-- `#axiomsClean` is a global command registered by importing
-- VeriTile.Meta.StatementAudit; fully-qualified names resolve without `open`.

-- VeriTile.Examples.ApproxGeLU
#axiomsClean VeriTile.Examples.approx_gelu_kernel_correct_view

-- VeriTile.Examples.FlashAttention1.Backward
#axiomsClean VeriTile.Examples.FA1Backward.attentionBackwardRealMasked_allVisible
#axiomsClean VeriTile.Examples.FA1Backward.attentionBackwardReal_eq_reverseMode
#axiomsClean VeriTile.Examples.FA1Backward.dQBlockContributionCausal_sum_eq_attentionBackwardRealCausal
#axiomsClean VeriTile.Examples.FA1Backward.dQBlockContributionMasked_sum_eq_attentionBackwardRealMasked
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQBoundaryDKernel_gridLaunched_backward_correct_of_owner_tail
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQBoundaryKernel_gridLaunched_backward_correct_of_owner_tail
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQCausalBoundaryDKernel_gridLaunched_backward_correct_of_owner_tail
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQCausalBoundaryKernel_gridLaunched_backward_correct_of_owner_tail
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQCausalKernel_gridLaunched_backward_correct
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQCausalKernel_gridLaunched_dQ_correct
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQCausalKernel_statefulTrace_blockContribution_from_inputs
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQCausalKernel_tailStores_readback_from_inputs
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQKernel_gridLaunched_backward_correct
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQKernel_gridLaunched_dQ_correct
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQKernel_gridLaunched_masked_dQ_correct
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQKernel_statefulTrace_blockContribution_from_inputs_of_exec
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardAtomicDQKernel_tailStores_readback_from_inputs
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardStrippedKernelStrided_realizes
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardStrippedKernelStrided_realizes_4D_fullSequence
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardStrippedKernelStrided_realizes_4D_queryBlock
#axiomsClean VeriTile.Examples.FA1Backward.fa1BackwardStrippedKernel_correct
#axiomsClean VeriTile.Examples.FA1Backward.gridLaunchedAtomic_boundaryD_backward_correct
#axiomsClean VeriTile.Examples.FA1Backward.gridLaunchedAtomic_boundary_backward_correct
#axiomsClean VeriTile.Examples.FA1Backward.gridLaunchedAtomic_causalBoundaryD_backward_correct
#axiomsClean VeriTile.Examples.FA1Backward.gridLaunchedAtomic_causalBoundary_backward_correct
#axiomsClean VeriTile.Examples.FA1Backward.gridLaunchedAtomic_causal_dQ_correct
#axiomsClean VeriTile.Examples.FA1Backward.gridLaunchedAtomic_masked_backward_correct
#axiomsClean VeriTile.Examples.FA1Backward.gridLaunchedAtomic_masked_dQ_correct
#axiomsClean VeriTile.Examples.FA1Backward.softmax_jvp_identity
#axiomsClean VeriTile.Examples.FA1Backward.streamingLSE_eq_lseReal

-- VeriTile.Examples.FlashAttention1.Backward.Math
#axiomsClean VeriTile.Examples.FA1Backward.attentionBackwardReal4DMasked_slice
#axiomsClean VeriTile.Examples.FA1Backward.attentionBackwardRealBoundaryD_eq_padded
#axiomsClean VeriTile.Examples.FA1Backward.attentionBackwardRealBoundary_eq_masked
#axiomsClean VeriTile.Examples.FA1Backward.attentionBackwardRealCausalBoundaryD_eq_padded
#axiomsClean VeriTile.Examples.FA1Backward.attentionBackwardRealCausalBoundary_eq_masked
#axiomsClean VeriTile.Examples.FA1Backward.causalBackward_block_tile_bridges_complete
#axiomsClean VeriTile.Examples.FA1Backward.causalBackward_tile_bridges_complete
#axiomsClean VeriTile.Examples.FA1Backward.dQBlockContributionBoundaryD_sum_eq_attentionBackwardRealBoundaryD
#axiomsClean VeriTile.Examples.FA1Backward.dQBlockContributionBoundary_sum_eq_attentionBackwardRealBoundary
#axiomsClean VeriTile.Examples.FA1Backward.dQBlockContributionCausalBoundaryD_sum_eq_attentionBackwardRealCausalBoundaryD
#axiomsClean VeriTile.Examples.FA1Backward.dQBlockContributionCausalBoundary_sum_eq_attentionBackwardRealCausalBoundary
#axiomsClean VeriTile.Examples.FA1Backward.maskedBackward_block_tile_bridges_complete

-- VeriTile.Examples.FlashAttention1.Core
#axiomsClean VeriTile.Examples.fa1_forward_correct_4D_causal_views
#axiomsClean VeriTile.Examples.fa1_forward_correct_4D_views

-- VeriTile.Examples.FlashAttention1.NaiveRefinement
#axiomsClean VeriTile.Examples.fa1_boundaryD_refines_naive_reference_views
#axiomsClean VeriTile.Examples.fa1_causal_boundaryD_refines_naive_reference_views

-- VeriTile.Examples.FlashAttention1.ScoreVariants.Backward
#axiomsClean VeriTile.Examples.FA1Score.gridLaunchedAtomic_alibiSlidingSoftcap_backward_correct
#axiomsClean VeriTile.Examples.FA1Score.gridLaunchedAtomic_alibi_backward_correct
#axiomsClean VeriTile.Examples.FA1Score.gridLaunchedAtomic_scoreVariant_backward_correct
#axiomsClean VeriTile.Examples.FA1Score.gridLaunchedAtomic_slidingWindow_backward_correct
#axiomsClean VeriTile.Examples.FA1Score.gridLaunchedAtomic_softcap_backward_correct

-- VeriTile.Examples.FlashAttention1.ScoreVariants.Math
#axiomsClean VeriTile.Examples.FA1Score.attentionBackwardRealAlibiSlidingSoftcap_eq_scoreVariant
#axiomsClean VeriTile.Examples.FA1Score.attentionBackwardRealAlibi_eq_scoreVariant
#axiomsClean VeriTile.Examples.FA1Score.attentionBackwardRealScoreVariant_dotScore_eq_masked
#axiomsClean VeriTile.Examples.FA1Score.attentionBackwardRealSlidingWindow_eq_scoreVariant
#axiomsClean VeriTile.Examples.FA1Score.attentionBackwardRealSoftcap_eq_scoreVariant
#axiomsClean VeriTile.Examples.FA1Score.dQBlockContributionAlibi_sum_eq_attentionBackwardRealAlibi
#axiomsClean VeriTile.Examples.FA1Score.dQBlockContributionScoreVariant_sum_eq_attentionBackwardRealScoreVariant
#axiomsClean VeriTile.Examples.FA1Score.dQBlockContributionSlidingWindow_sum_eq_attentionBackwardRealSlidingWindow
#axiomsClean VeriTile.Examples.FA1Score.dQBlockContributionSoftcap_sum_eq_attentionBackwardRealSoftcap

-- VeriTile.Examples.FlashAttention2
#axiomsClean VeriTile.Examples.fa1_backward_eq_fa2_backward
#axiomsClean VeriTile.Examples.fa1_backward_eq_fa2_backward4D
#axiomsClean VeriTile.Examples.fa1_causal_backward_eq_fa2_causal_backward
#axiomsClean VeriTile.Examples.fa1_causal_backward_eq_fa2_causal_backward4D
#axiomsClean VeriTile.Examples.fa1_eq_fa2_two_block_forward4D
#axiomsClean VeriTile.Examples.fa2BackwardAtomicDQCausalKernel_gridLaunched_backward_correct
#axiomsClean VeriTile.Examples.fa2BackwardAtomicDQCausalTwoBlockKernel_gridLaunched_backward_correct
#axiomsClean VeriTile.Examples.fa2BackwardAtomicDQCausalTwoBlockPartitionKernel_gridLaunched_backward_correct
#axiomsClean VeriTile.Examples.fa2BackwardAtomicDQCausalTwoBlockPartitionKernel_gridLaunched_backward_correct_4D_slice
#axiomsClean VeriTile.Examples.fa2BackwardAtomicDQCausalTwoBlockPartitionKernel_statefulTrace_blockContribution_from_inputs
#axiomsClean VeriTile.Examples.fa2BackwardAtomicDQKernel_gridLaunched_backward_correct
#axiomsClean VeriTile.Examples.fa2BackwardAtomicDQKernel_gridLaunched_dQ_correct
#axiomsClean VeriTile.Examples.fa2BackwardAtomicDQTwoBlockKernel_gridLaunched_backward_correct
#axiomsClean VeriTile.Examples.fa2BackwardAtomicDQTwoBlockPartitionKernel_gridLaunched_backward_correct
#axiomsClean VeriTile.Examples.fa2BackwardAtomicDQTwoBlockPartitionKernel_gridLaunched_backward_correct_4D_slice
#axiomsClean VeriTile.Examples.fa2BackwardAtomicDQTwoBlockPartitionKernel_statefulTrace_blockContribution_from_inputs_of_exec
#axiomsClean VeriTile.Examples.fa2ScalarFragmentSummaryKernel_correct_view
#axiomsClean VeriTile.Examples.fa2ScalarMergedMaxKernel_correct_view
#axiomsClean VeriTile.Examples.fa2ScalarMergedMaxKernel_loaded_of_agrees
#axiomsClean VeriTile.Examples.fa2ScalarScoreMaxKernel_correct_view
#axiomsClean VeriTile.Examples.fa2ScalarScoreMaxKernel_loaded_of_agrees
#axiomsClean VeriTile.Examples.fa2ScalarTwoBlockForwardKernel_attentionReal4D_view
#axiomsClean VeriTile.Examples.fa2ScalarTwoBlockForwardKernel_attentionReal_of_score_producers_view
#axiomsClean VeriTile.Examples.fa2ScalarTwoBlockForwardKernel_attentionReal_of_score_value_max_merged_producers_view
#axiomsClean VeriTile.Examples.fa2ScalarTwoBlockForwardKernel_attentionReal_of_score_value_max_producers_view
#axiomsClean VeriTile.Examples.fa2ScalarTwoBlockForwardKernel_attentionReal_of_score_value_producers_view
#axiomsClean VeriTile.Examples.fa2ScalarTwoBlockForwardKernel_attentionReal_view
#axiomsClean VeriTile.Examples.fa2ScalarTwoBlockForwardKernel_correct_view
#axiomsClean VeriTile.Examples.fa2ScalarTwoBlockForwardKernel_forAll_attentionReal4D_view
#axiomsClean VeriTile.Examples.fa2ScalarTwoFragmentMergeKernel_attentionReal_view
#axiomsClean VeriTile.Examples.fa2ScalarTwoFragmentMergeKernel_correct_view
#axiomsClean VeriTile.Examples.fa2ScalarValueFragmentKernel_correct_view
#axiomsClean VeriTile.Examples.fa2ScalarValueFragmentKernel_loaded_of_agrees
#axiomsClean VeriTile.Examples.fa2ScalarValueFragmentKernel_twoBlock_loaded_of_agrees
#axiomsClean VeriTile.Examples.fa2ScoreFragmentKernel_correct_view
#axiomsClean VeriTile.Examples.fa2ScoreFragmentKernel_scaledScore_correct_view
#axiomsClean VeriTile.Examples.fa2ScoreFragmentKernel_scaledScore_row_loaded
#axiomsClean VeriTile.Examples.fa2ScoreFragmentKernel_scaledScore_row_loaded_of_agrees
#axiomsClean VeriTile.Examples.fa2ScoreFragmentKernel_twoBlock_rows_loaded_of_agrees
#axiomsClean VeriTile.Examples.fa2ScoreFragmentSpec_eq_scaledScore
#axiomsClean VeriTile.Examples.fa2_delayed_rescale_sum_eq
#axiomsClean VeriTile.Examples.fa2_delayed_rescale_weighted_sum_eq
#axiomsClean VeriTile.Examples.fa2_forward_correct_4D_views
#axiomsClean VeriTile.Examples.fa2_masked_sum_eq_zero_of_all_invisible
#axiomsClean VeriTile.Examples.fa2_masked_weighted_sum_eq_zero_of_all_invisible
#axiomsClean VeriTile.Examples.fa2_score_fragment_tile_eq
#axiomsClean VeriTile.Examples.fa2_two_block_backward_dQ4D_eq_fa1_backward4D
#axiomsClean VeriTile.Examples.fa2_two_block_backward_dQ4D_eq_fa2_backward4D
#axiomsClean VeriTile.Examples.fa2_two_block_backward_dQ_eq_fa1_backward
#axiomsClean VeriTile.Examples.fa2_two_block_backward_dQ_eq_fa2_backward
#axiomsClean VeriTile.Examples.fa2_two_block_causal_backward_dQ4D_eq_fa2_causal_backward4D
#axiomsClean VeriTile.Examples.fa2_two_block_causal_backward_dQ_eq_fa2_causal_backward
#axiomsClean VeriTile.Examples.fa2_two_block_forward_eq_attentionReal
#axiomsClean VeriTile.Examples.fa2_two_block_forward_eq_attentionReal4D
#axiomsClean VeriTile.Examples.fa2_two_fragment_attention_ratio_eq_flat
#axiomsClean VeriTile.Examples.fa2_two_fragment_denominator_merge_eq_flat
#axiomsClean VeriTile.Examples.fa2_two_fragment_numerator_merge_eq_flat

-- VeriTile.Triton.Launch.Blocked1D
#axiomsClean VeriTile.Triton.Blocked1D.launch_of_frames

-- VeriTile.Triton.Launch.Blocked1DConfig
#axiomsClean VeriTile.Triton.Blocked1DLaunch.check_complete
#axiomsClean VeriTile.Triton.Blocked1DLaunch.check_ok

-- VeriTile.Triton.Launch.Blocked1DFlat
#axiomsClean VeriTile.Triton.Blocked1D.launch_of_frames_addr

-- VeriTile.Triton.Launch.Blocked1DWrapper
#axiomsClean VeriTile.Triton.Elementwise2.check_complete
#axiomsClean VeriTile.Triton.Elementwise2.check_ok
#axiomsClean VeriTile.Triton.Elementwise2.launchDim0_not_covered

-- VeriTile.Triton.Launch.Line3
#axiomsClean VeriTile.Triton.Blocked1D.mergeFrames_liftFrames

-- VeriTile.Triton.Launch.Relational
#axiomsClean VeriTile.Triton.Blocked1D.fused_agrees_two_launch
#axiomsClean VeriTile.Triton.Blocked1D.launch_of_programRuns

-- VeriTile.Triton.Launch.Serial
#axiomsClean VeriTile.Triton.Kernel.runSerial_agrees_merge

-- VeriTile.Triton.Launch.StridedUnary
#axiomsClean VeriTile.Triton.StridedUnary.check_complete
#axiomsClean VeriTile.Triton.StridedUnary.check_ok

-- VeriTile.Triton.Launch.StridedUnaryFlat
#axiomsClean VeriTile.Triton.StridedUnary.Pre.addr_bytes
#axiomsClean VeriTile.Triton.StridedUnary.Pre.flat_disjoint
#axiomsClean VeriTile.Triton.StridedUnary.Pre.reads_outside_writes

