#!/usr/bin/env python3
"""Render bench/optimizations/inductor_narrow/RESULTS.md from launch_evidence/inductor_narrow.json.

Every number comes from the evidence file. The decision and the diagnosis verdicts are the ones the harness computed
with its pre-registered rules (docstring of scripts/launch_inductor_narrow.py); their inputs are shown next to them.

    python3 scripts/inductor_narrow_report.py [--check]
"""
from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
EV = REPO / "bench/tritonbench_g/add_example/launch_evidence/inductor_narrow.json"
OUT = REPO / "bench/optimizations/inductor_narrow/RESULTS.md"
CFG = ["B0", "N", "N1", "static"]


def med(x):
    return statistics.median(x)


def f(x, nd=2):
    return "—" if x is None else (f"{x:.{nd}f}" if isinstance(x, (int, float)) else str(x))


def render() -> str:
    d = json.loads(EV.read_text())
    order = [tuple(s) for s in d["order"]]
    dec = d["decision"]
    L = ["# Stage 13 results: N1 against guarded N, and the sustained-time diagnosis", "",
         "Generated by `scripts/inductor_narrow_report.py` from `launch_evidence/inductor_narrow.json`. Do not edit by hand.",
         "", f"Host: {d['gpu_name']}, torch {d['torch']}, Triton {d['triton']}, bf16.",
         f"Run: {len(order)} shapes, 4 configurations × 2 modes (`auto` is autotuned, `fixed` is one config) × 2 rounds;",
         "one process per configuration. The criterion was fixed before the run.", "",
         f"## Decision (pre-registered, `auto` mode): **{dec['outcome']}**", "",
         "| round | (a) T(B0)/T(N1) ≥ 1.10 | (b) T(N)/T(N1) ≥ 0.99, worst shape ≥ 0.97 | (c) T(N)/T(N1) ≥ 1.03 |",
         "|---|---|---|---|"]
    for i, r in enumerate(dec["per_round"]):
        L.append(f"| {i + 1} | {f(r.get('a_T_B0_over_N1'), 3)}× → {r['a']} | {f(r.get('b_T_N_over_N1'), 3)}× "
                 f"(worst {f(r.get('b_worst_shape'), 3)}×) → {r['b']} | {r['c']} |")
    L += ["", "## Validity (`auto` mode)", "", "| config | round | checks | valid |", "|---|---|---|---|"]
    for i, r in enumerate(dec["per_round"]):
        for c in CFG:
            v = r["validity"].get(c)
            if v:
                L.append(f"| {c} | {i + 1} | {', '.join(f'{k}={x}' for k, x in v.items() if k != 'valid')} | **{v['valid']}** |")
    L += ["", "## Complete-sequence time T (ms, median of 5 warm passes)", "",
          "| config | auto r1 | auto r2 | fixed r1 | fixed r2 | cold pass auto r1 (s) |", "|---|---|---|---|---|---|"]
    idx = {(r["config"], r["mode"], k): r for k, rd in enumerate(d["rounds"]) for r in rd}
    for c in CFG:
        cells = []
        for mode in ("auto", "fixed"):
            for k in (0, 1):
                r = idx.get((c, mode, k))
                cells.append("error" if (r is None or "error" in r) else f"{med(p['pass_s'] for p in r['warm']) * 1e3:.1f}")
        r0 = idx.get((c, "auto", 0))
        L.append(f"| {c} | " + " | ".join(cells) + f" | {f(r0.get('cold_pass_s') if r0 and 'error' not in r0 else None)} |")
    # artifacts
    L += ["", "## Timed artifacts (round 1): autotuned or fixed config, registers, SASS, cubin", "",
          "| config | mode | kernel | XBLOCK | warps | regs | spills | SASS instr | CALL | cubin sha256 (16) |",
          "|---|---|---|---|---|---|---|---|---|---|"]
    for mode in ("auto", "fixed"):
        for c in ("B0", "N", "N1"):
            r = idx.get((c, mode, 0))
            if not r or "error" in r:
                continue
            for a in r.get("artifacts", []):
                sass = a.get("sass", {})
                L.append(f"| {c} | {mode} | {a['kernel']} | {a['config']['kwargs'].get('XBLOCK')} | {a['config']['num_warps']} | "
                         f"{a.get('n_regs')} | {a.get('n_spills')} | {sass.get('instructions')} | {sass.get('CALL')} | "
                         f"{(a.get('cubin_sha256') or '')[:16]} |")
    # per-shape
    L += ["", "## Per shape (`auto`, mean of 2 rounds): in-sequence µs/call; isolated device µs; idle-probe µs", "",
          "| shape | " + " | ".join(f"{c} seq | {c} iso | {c} idle" for c in ("B0", "N", "N1")) + " |",
          "|" + "---|" * 10]
    for i, s in enumerate(order):
        cells = []
        for c in ("B0", "N", "N1"):
            rs = [idx.get((c, "auto", k)) for k in (0, 1)]
            if any(r is None or "error" in r for r in rs):
                cells += ["—"] * 3
                continue
            cells.append(f"{statistics.mean(med(p['per_call_ms'][i] for p in r['warm']) for r in rs) * 1e3:.0f}")
            cells.append(f"{statistics.mean(r['profile_isolated'][i]['kernel_us'] for r in rs):.0f}")
            cells.append(f"{statistics.mean(r['idle_probe'][i]['event_us'] for r in rs):.0f}")
        L.append(f"| {s[0]} × {s[1]} | " + " | ".join(cells) + " |")
    # diagnosis
    L += ["", "## Sustained vs device time: diagnosis (pre-registered rules, `auto` round 1)", "",
          "| config | k_seq / k_iso | SM clock warm / idle | max limit-reason fraction | gap fraction | verdict |",
          "|---|---|---|---|---|---|"]
    for c, g in dec["diagnosis"].items():
        L.append(f"| {c} | {f(g['k_seq_over_k_iso_median'], 3)} | {f(g['sm_clock_warm_over_idle'], 3)} | "
                 f"{f(g['limit_reason_max_fraction'], 2)} | {f(g['gap_fraction'], 3)} | **{g['verdict']}** |")
    L += ["", "Telemetry (round 1, `auto`):", ""]
    for c in CFG:
        r = idx.get((c, "auto", 0))
        if r and "error" not in r:
            L.append(f"- **{c}**: ok={r['telemetry_ok']} {r.get('telemetry_error') or ''}; warm {r['telemetry']['warm']}; "
                     f"idle {r['telemetry']['idle']}")
    r = idx.get(("B0", "auto", 0))
    if r and "error" not in r:
        L.append(f"- static NVML: {r.get('telemetry_static')}")
    # fallback
    L += ["", "## Beyond-guard shape (numel = 2^31), round 1 `auto`", ""]
    for c in ("B0", "N", "N1"):
        r = idx.get((c, "auto", 0))
        fb = (r or {}).get("fallback")
        if fb:
            L.append(f"- **{c}**: bitwise={fb.get('bitwise_equal_eager')}, any rewrite fired={fb.get('any_rewrite_fired')}, "
                     f"kernels defined={[(k.get('kernel_name'), k.get('xnumel_type'), k.get('rewritten'), k.get('reason')) for k in fb.get('kernels_defined', [])]}, "
                     f"peak GB={f(fb.get('max_memory_gb'))}" + (f", error: {fb['error'][-300:]}" if "error" in fb else ""))
            if fb.get("recompile_log"):
                L.append(f"  - recompile: `{fb['recompile_log'][0][:220]}`")
    # N1 eligibility record
    r = idx.get(("N1", "auto", 0))
    if r and "error" not in r:
        L += ["", "## N1 eligibility as logged at codegen (round 1 `auto`)", ""]
        for e in r["hook_events"]:
            el = e.get("eligibility", {})
            L.append(f"- `{e.get('kernel_name')}`: rewritten={e.get('rewritten')}; checks={el.get('checks')}; "
                     f"ks={el.get('ks_exprs')}; guard=`{el.get('guard_text')}`")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else 1)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO)}")
