#!/usr/bin/env python3
"""Render bench/optimizations/inductor_divmod/RESULTS.md from launch_evidence/inductor_divmod.json.

Every number is read from the evidence file; the decision is the one the harness computed with the
pre-registered criterion (scripts/launch_inductor_divmod.py docstring), shown next to its inputs.

    python3 scripts/inductor_divmod_report.py [--check]
"""
from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
EV = REPO / "bench/tritonbench_g/add_example/launch_evidence/inductor_divmod.json"
OUT = REPO / "bench/optimizations/inductor_divmod/RESULTS.md"
ORDERED = ["eager", "dyn_explicit", "dyn_auto", "static_cached", "dyn_N", "dyn_F", "dyn_NF", "standalone_B"]
LABEL = {"eager": "eager", "dyn_explicit": "dyn (B0)", "dyn_auto": "auto-dyn", "static_cached": "static cached",
         "dyn_N": "dyn + N", "dyn_F": "dyn + F", "dyn_NF": "dyn + NF", "standalone_B": "stage-11 B"}


def med(xs):
    return statistics.median(xs)


def by_config(rd):
    return {r["config"]: r for r in rd}


def render() -> str:
    d = json.loads(EV.read_text())
    rounds = [by_config(rd) for rd in d["rounds"]]
    dec = d["decision"]
    order = [tuple(s) for s in d["order"]]
    L = ["# Stage 12 results: does the fast division transfer into Inductor's kernel?", "",
         "Generated by `scripts/inductor_divmod_report.py` from `launch_evidence/inductor_divmod.json`. Do not edit by hand.",
         "",
         f"Host: {d['gpu_name']} (Modal; nproc {d['cpu'].split()[-1]}), torch {d['torch']}, Triton {d['triton']}, bf16.",
         f"Run: {len(order)} shapes in a changing order, in one process per configuration. {d['calls']} calls per shape per pass,",
         f"{d['warm_passes']} warm passes, {len(rounds)} rounds; round 2 runs the configurations in reverse order.",
         "The criterion was fixed before the run; it is in the `launch_inductor_divmod.py` docstring.", "",
         "Configurations:",
         "- **B0** is Inductor's dynamic kernel as emitted.",
         "- **N** narrows the i64 size scalars to int32.",
         "- **F** replaces the per-element `%` and `//` with the proved in-kernel fast divmod.",
         "- **NF** does both.",
         "- In N, F and NF the original body is kept verbatim under the guard's `else` branch.", "",
         f"## Decision (pre-registered): **{dec['outcome']}**"
         + (f", selected `{dec['selected']}`" if dec.get("selected") else ""), "",
         "| variant | round | T(B0)/T(V) | worst shape S(B0)/S(V) | (a) ≥1.10 | (b) ≤ auto & eager | (c) ≥0.95 | pass |",
         "|---|---|---|---|---|---|---|---|"]
    for i, pr in enumerate(dec["per_round"]):
        for V, r in pr["per_variant"].items():
            if "speedup_vs_B0" in r:
                L.append(f"| {V} | {i + 1} | {r['speedup_vs_B0']:.3f}× | {r['worst_shape_ratio']:.3f}× | {r['a']} | "
                         f"{r['b']} | {r['c']} | **{r['pass']}** |")
            else:
                L.append(f"| {V} | {i + 1} | — | — | — | — | — | {r['why']} |")
    L += ["", "## Validity per configuration", "", "| config | round | " + " | ".join(
        ["bitwise all", "no warm compiles", "rewrite fired", "same compile count as B0", "valid"]) + " |",
          "|---|---|---|---|---|---|---|"]
    for i, pr in enumerate(dec["per_round"]):
        for c in ORDERED:
            v = pr["validity"].get(c)
            if v is None:
                continue
            L.append(f"| {LABEL[c]} | {i + 1} | {v.get('bitwise_all', '—')} | {v.get('no_warm_compiles', '—')} | "
                     f"{v.get('rewrite_fired_on_all_divmod_kernels', '—')} | {v.get('same_compile_count_as_B0', '—')} | "
                     f"**{v['valid']}** |")
    L += ["", "## Complete-sequence time and compile cost", "",
          "- **T:** the warm complete-sequence time, median over the warm passes: one pass is 14 shapes × 20 calls with a",
          "  single synchronize at the end.",
          "- **cold:** the first pass, including every compile.",
          "- **Dynamo graphs** and **kernels defined** are counted over the whole process.", "",
          "| config | T r1 (ms) | T r2 (ms) | cold r1 (s) | cold r2 (s) | Dynamo graphs | kernels defined | process (s) |",
          "|---|---|---|---|---|---|---|---|"]
    for c in ORDERED:
        rs = [r.get(c) for r in rounds]
        if any(r is None or "error" in r for r in rs):
            err = next((r.get("error", "") for r in rs if r and "error" in r), "missing")
            L.append(f"| {LABEL[c]} | error: `{err.strip().splitlines()[-1][:80] if err else ''}` | | | | | | |")
            continue
        T = [med(p["pass_s"] for p in r["warm"]) * 1e3 for r in rs]
        L.append(f"| {LABEL[c]} | {T[0]:.1f} | {T[1]:.1f} | {rs[0]['cold_pass_s']:.2f} | {rs[1]['cold_pass_s']:.2f} | "
                 f"{rs[0]['counters_final']['unique_graphs']} | {len(rs[0].get('hook_events', [])) or '—'} | "
                 f"{rs[0]['process_s']:.0f} |")
    # per-shape tables (round 1 and round 2 medians averaged)
    def per_shape(metric):
        rows = []
        for c in ORDERED:
            rs = [r.get(c) for r in rounds]
            if any(r is None or "error" in r for r in rs):
                continue
            vals = []
            for i, s in enumerate(order):
                if metric == "S":
                    x = [med(p["per_call_ms"][i] for p in r["warm"]) * 1e3 for r in rs]
                elif metric == "kernel":
                    x = [r["profile"][i]["kernel_us"] for r in rs]
                elif metric == "host":
                    x = [r["single"][i]["host_us"] for r in rs]
                else:
                    x = [r["single"][i]["wall_us"] for r in rs]
                vals.append(statistics.mean(x))
            rows.append((c, vals))
        return rows
    for metric, title in (("S", "In-sequence time per call (µs; CUDA events around each shape's 20 calls; mean of the two rounds)"),
                          ("kernel", "Device time per call (µs; summed CUDA kernel time from torch.profiler; mean of the two rounds)"),
                          ("host", "Host return time per call (µs; from call to return, before synchronize; mean of the two rounds)"),
                          ("wall", "Single-call wall time (µs; call then synchronize; mean of the two rounds)")):
        L += ["", f"## {title}", "", "| shape | " + " | ".join(LABEL[c] for c, _ in per_shape(metric)) + " |",
              "|" + "---|" * (1 + len(per_shape(metric)))]
        rows = per_shape(metric)
        for i, s in enumerate(order):
            L.append(f"| {s[0]} × {s[1]} | " + " | ".join(f"{v[i]:.1f}" for _, v in rows) + " |")
    # kernel identities and rewrite events
    L += ["", "## Kernel identities and rewrite events (round 1)", ""]
    for c in ORDERED:
        r = rounds[0].get(c)
        if not r or "error" in r:
            continue
        names = sorted({k for p in r["profile"] for k in p["kernels"]})
        L.append(f"- **{LABEL[c]}**: device kernels {names}")
        for e in r.get("hook_events", []):
            L.append(f"  - define_kernel `{e.get('kernel_name')}`: divmod={e.get('has_divmod')}, "
                     f"rewritten={e.get('rewritten')}, before {e.get('before')} → after {e.get('after', e.get('before'))}"
                     + (f", reason: {e['reason']}" if e.get("reason") and not e.get("rewritten") else ""))
        if r.get("recompile_log"):
            L.append(f"  - recompile log ({len(r['recompile_log'])} records), first: `{r['recompile_log'][0][:160]}`")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else 1)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO)}")
