#!/usr/bin/env python3
"""Generate the authoritative release record for the launch-checker work from
the evidence files only (no hand-written numbers).

    python3 scripts/launch_release_record.py [--out RELEASE_RECORD.md] [--branch B ...]

Every figure below is read from `launch_evidence/*.json`. For each evidence
file the record states whether its `input_hashes` match the current working
tree, so a reader can see exactly which sources each check covered. Branch
rows give the head commit and tree hash; equal tree hashes mean identical
content.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))
import launch_local_check as LC  # noqa: E402

EVID = LC.EVID


def git(*a: str) -> str:
    return subprocess.run(["git", *a], cwd=REPO, capture_output=True, text=True).stdout.strip()


def load(name: str) -> dict | None:
    f = EVID / name
    return json.loads(f.read_text()) if f.exists() else None


def freshness(ev: dict | None, hashes: dict, name: str = "") -> str:
    """Current iff every file this evidence depends on (LC.evidence_deps: a
    declared subset, or the whole input set) has the hash its record states."""
    if ev is None:
        return "absent"
    if not ev.get("input_hashes"):
        return "no input hashes"
    current, stale, unhashed = LC.evidence_freshness(name, ev, hashes)
    scope = "whole input set" if LC.evidence_deps(name) is None else f"{len(LC.evidence_deps(name))} dependencies"
    if current:
        return f"current ({scope})"
    out = []
    if stale:
        out.append("changed: " + ", ".join(stale))
    if unhashed:
        out.append("not hashed by the record: " + ", ".join(unhashed))
    return f"STALE ({scope}) — " + "; ".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=Path("/dev/stdout"))
    ap.add_argument("--branch", action="append", default=[])
    a = ap.parse_args()
    hashes = LC.input_hashes()
    L = []
    w = L.append
    head = git("rev-parse", "HEAD")
    w("# Release record — host-launch checker (generated)\n")
    w(f"Generated by `scripts/launch_release_record.py` from `launch_evidence/`. Working tree HEAD "
      f"`{head[:12]}`, tree `{git('rev-parse', 'HEAD^{tree}')[:12]}`"
      f"{' (uncommitted changes present)' if git('status', '--porcelain') else ''}.\n")
    if a.branch:
        w("| branch | head | tree |\n|---|---|---|")
        for b in a.branch:
            w(f"| `{b}` | `{git('rev-parse', b)[:12]}` | `{git('rev-parse', b + '^{tree}')[:12]}` |")
        w("")

    w("## Hashed inputs (current tree)\n")
    w("| file | sha256 |\n|---|---|")
    for k, v in sorted(hashes.items()):
        w(f"| `{k}` | `{v[:16]}` |")
    w("")

    led = load("ledger.json")
    w("## Local gate (`launch_local_check.py`)\n")
    if led:
        w(f"Ledger generated {led['generated']} at git head `{led['git_head'][:12]}`; fresh workspace: "
          f"{led.get('fresh_workspace')}; ledger inputs: {freshness(led, hashes, "ledger.json")}.\n")
        w("| step | status | reason |\n|---|---|---|")
        for k, s in led["steps"].items():
            w(f"| {k} | {s['status']} | {s.get('reason') or s.get('evidence', '')} |")
        w("")

    oc = load("official_comparator.json")
    w("## Official comparator and upstream gates (Linux container)\n")
    if oc:
        w(f"Audited commit `{oc['audited_commit'][:12]}`; exit_code {oc['exit_code']}; inputs: "
          f"{freshness(oc, hashes, "official_comparator.json")}. Environment: {oc['environment']}. Tools: {oc['tools']}.\n")
        w("| target | mode | theorems accepted |\n|---|---|---|")
        for r in oc["results"].values():
            w(f"| {r['source']} | {r['mode']} | {r['theorem_count'] if r['accepted'] else 'REJECTED'} |")
        for g, r in (oc.get("whole_library_gates") or {}).items():
            w(f"| {g} | — | exit {r['exit_code']} |")
        w(f"\nNot run: {'; '.join(oc.get('not_run', [])) or 'none'}.\n")

    ad = load("adapter_results.json")
    w("## Source-link adapter verdicts (`adapter_results.json`)\n")
    if ad:
        n = sum(len(r.get("cases", {})) for r in ad.values())
        acc = sum(c["accepted"] for r in ad.values() for c in r.get("cases", {}).values())
        wf = sum(bool(c.get("wrapper_failures")) for r in ad.values() for c in r.get("cases", {}).values())
        w(f"{len(ad)} manifests, {n} configurations: {acc} accepted by the checker (kernel-checked), "
          f"{n - acc} rejected with named obligations; {wf} with an adapter wrapper-obligation failure "
          f"(W1/W2). Metadata comes from CPU tensors the adapter builds from each manifest spec, or from "
          f"supplied dicts — not from a live invocation.\n")

    mu = load("mutation_results.json")
    w("## Adversarial suite (`mutation_results.json`)\n")
    if mu:
        c = mu["counts"]
        w(f"{sum(c.values())} cases, undetected: {len(mu['undetected'])}; inputs: {freshness(mu, hashes, "mutation_results.json")}. "
          "Classes (these are not all bugs found):\n")
        desc = {"accepted": "valid controls and benign edits that must be accepted",
                "violated_obligation": "configurations/mutants rejected by a named obligation",
                "concrete_witness": "counterexamples (Lean-checked or labelled emulator-only)",
                "unsupported_input": "sources outside the adapter's recognized fragment",
                "evidence_rejection": "evidence-integrity checks (statement, axiom, hash, pin gates)",
                "infrastructure_failure": "intended tool-unavailable control"}
        for k, v in c.items():
            w(f"- {v} {k}: {desc.get(k, '')}")
        w("")

    w("## Execution evidence\n")
    w("| evidence | backend | result | inputs |\n|---|---|---|---|")
    it = load("interpreter.json")
    if it:
        w(f"| interpreter.json | Triton {it['triton']} CPU interpreter | exit {it['exit_code']}; "
          + "; ".join(f"{Path(k).name}: {'pass' if v['passed'] else 'FAIL'} ({v['source']})"
                      for k, v in it["cases"].items()) + f" | {freshness(it, hashes, "interpreter.json")} |")
    w1 = load("w1_probe_vector_addition_custom.json")
    if w1:
        w(f"| w1_probe_vector_addition_custom.json | Triton {w1['triton']} CPU interpreter | W1 partial output "
          f"reproduced: {w1['w1_finding_confirmed']} | no hash record (interpreter probe) |")
    g, gp, gx = load("gpu.json"), load("gpu_perf.json"), load("gpu_extras.json")
    if g:
        w(f"| gpu.json | {g.get('gpu_name')} CC {g.get('compute_capability')}, Triton {g['triton']}, "
          f"torch {g['torch']} | exit {g['exit_code']}; {sum(1 for c in g.get('cases', {}).values() if c['bitwise_equal'] and c['sentinels_intact'])}"
          f"/{len(g.get('cases', {}))} cases bitwise equal with intact sentinels | {freshness(g, hashes, "gpu.json")} |")
    if gp:
        w(f"| gpu_perf.json | same device | exit {gp['exit_code']}; kernel n={gp['n']} median "
          f"{gp['kernel_steady_state']['median_ms']:.3f} ms; torch x+y {gp['torch_x_plus_y_reference']['median_ms']:.3f} ms "
          f"| {freshness(gp, hashes, "gpu_perf.json")} |")
    if gx:
        w(f"| gpu_extras.json | same device | vector_addition_custom passed: {gx['vector_addition_custom']['passed']}; "
          f"W1 partial output reproduced on GPU: {gx['w1_probe']['w1_finding_confirmed']} | {freshness(gx, hashes, "gpu_extras.json")} |")
    bs = load("block_sweep.json")
    if bs:
        w(f"| block_sweep.json | same device class | selected BLOCK {bs['selected_block']}; all correct: "
          f"{all(v['correct'] for v in bs['blocks'].values())} | {freshness(bs, hashes, "block_sweep.json")} |")
    for fname, label in (("invoke_interpreter.json", "Triton CPU interpreter"),
                         ("gpu_wrapper.json", "CUDA")):
        iv = load(fname)
        if not iv:
            continue
        backend = (f"{iv.get('gpu_name')} CC {iv.get('compute_capability')}, " if iv.get("gpu_name") else "") \
            + f"{label}, Triton {iv['triton']}, torch {iv['torch']}"
        n_ok = sum(bool(r["as_expected"]) for r in iv["cases"])
        complete = ("case list complete" if "missing_cases" in iv and not (iv["missing_cases"] or iv.get("unexpected_cases"))
                    else "case-list completeness not recorded (older harness)")
        pin = iv.get("relu_pinned_text") or {}
        pinned = (f"pinned ReLU text: {pin.get('status')} ({pin.get('error_type')})" if pin
                  else "pinned ReLU text: " + (lambda t: t[t.find("AttributeError"):].split("')")[0]
                                               if "AttributeError" in t else t)(
                      iv.get("relu_pinned_on_device") or "not probed"))
        w(f"| {fname} | {backend} | {n_ok}/{len(iv['cases'])} as expected; all_as_expected "
          f"{iv['all_as_expected']}; {complete}; {pinned}; ReLU text run: {iv.get('relu_source')} "
          f"| {freshness(iv, hashes, fname)} |")
    for fname, what in (("invoke_differential.json", "Elementwise2 mirror vs Lean #eval"),
                        ("invoke_differential_strided.json", "StridedUnary mirror vs Lean #eval")):
        dv = load(fname)
        if dv:
            w(f"| {fname} | host | {what}: {dv['cases']} cases, {len(dv['mismatches'])} mismatches "
              f"| {freshness(dv, hashes, fname)} |")
    rt = load("relu_tune.json")
    if rt:
        w(f"| relu_tune.json | {rt.get('gpu_name')} CC {rt.get('compute_capability')}, Triton {rt['triton']}, "
          f"torch {rt['torch']} | checked ReLU num_warps sweep {rt['search_space']['num_warps']}: all correct "
          f"{rt['all_correct']}; selected num_warps {rt.get('selected_num_warps')} ({rt.get('selection_rule')}) "
          f"| {freshness(rt, hashes, 'relu_tune.json')} |")
    fb = load("fusion_bench.json")
    if fb:
        big = [x for x in fb["summary"]["per_size"] if x["n"] >= 2 ** 24]
        sp = "; ".join(f"n={x['n']}: device x{x['device_speedup_fused_vs']['unfused_checked']:.2f} vs unfused, "
                       f"x{x['device_speedup_fused_vs']['compiled']:.2f} vs compiled; end-to-end "
                       f"x{x['e2e_speedup_fused_vs']['unfused_checked']:.2f} / x{x['e2e_speedup_fused_vs']['compiled']:.2f}"
                       for x in big)
        w(f"| fusion_bench.json | {fb.get('gpu_name')}, Triton {fb['triton']}, torch {fb['torch']} | correctness "
          f"{fb['correctness_ok']}; {sp}; regressions listed: "
          f"{len(fb['summary']['regressions_fused_slower_by_more_than_2pct'])} | {freshness(fb, hashes, 'fusion_bench.json')} |")
    ov = load("invoke_overhead.json")
    if ov:
        r0 = ov["rows"][0]
        w(f"| invoke_overhead.json | {ov['host']}, torch {ov['torch']} | host-side check cost only (kernel "
          f"not included): elementwise metadata {r0['tensor_meta_x3_us']:.1f} µs + decision "
          f"{r0['contract_decision_us']:.1f} µs; strided metadata "
          f"{ov['strided_relu']['storage_meta_x2_us']:.1f} µs + decision "
          f"{ov['strided_relu']['contract_decision_us']:.1f} µs | {freshness(ov, hashes, 'invoke_overhead.json')} |")
    w("\nFreshness is judged per evidence file against the files it depends on "
      "(`launch_local_check.evidence_deps`); the official comparator, ledger and mutation suite "
      "depend on the whole input set. GPU results describe one device and one software stack; "
      "interpreter results are interpreter evidence only.\n")
    a.out.write_text("\n".join(L) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
