#!/usr/bin/env python3
"""Local verification for the host-launch checker and its add_example case.

Separately named from the upstream release gates (`scripts/check-artifact.sh`,
`bench/audit_trust.sh`), which require the official comparator on Linux and
are neither weakened nor replaced here.

    python3 scripts/launch_local_check.py                 # local gates -> LOCAL_CHECKS_PASSED
    python3 scripts/launch_local_check.py --require-official   # also demand a fresh official comparator result
    python3 scripts/launch_local_check.py --require-gpu        # also demand fresh GPU correctness+perf results

Every step is recorded in the ledger (`--ledger`, default
bench/tritonbench_g/add_example/launch_evidence/ledger.json) with status,
scope, assumptions, evidence and input hashes. Official/GPU evidence is read
from `launch_evidence/official_comparator.json` and `launch_evidence/gpu.json`;
missing, stale (hash mismatch) or unsuccessful evidence is `not_run`/`failed`
and makes the corresponding `--require-*` invocation fail.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))
sys.path.insert(0, str(REPO / "bench"))
import audit_source  # noqa: E402
import launch_check  # noqa: E402

KDIR = REPO / "bench/tritonbench_g/add_example"
EVID = KDIR / "launch_evidence"
FROZEN = EVID / "frozen"
NEW_LEAN = ["VeriTile/Triton/Launch/Blocked1DConfig.lean",
            "VeriTile/Triton/Launch/Blocked1D.lean",
            "VeriTile/Triton/Launch/Serial.lean",
            "VeriTile/Triton/Launch/Blocked1DWrapper.lean",
            "VeriTile/Triton/Launch/Blocked1DFlat.lean",
            "VeriTile/Triton/Launch/Composition.lean",
            "bench/tritonbench_g/add_example/AddExample.lean",
            "bench/tritonbench_g/vector_addition_custom/VectorAdditionCustom.lean",
            "bench/tests/Blocked1DLaunchWitnesses.lean"]
VAC = "VeriTile.Bench.TritonBenchG.VectorAdditionCustom"
WIT = "VeriTile.Bench.Tests.Blocked1DLaunchWitnesses"
# (file, namespace for the inventory, theorems that must be axiom-clean, required inventory)
AUDIT_TARGETS = None  # filled after HEADLINES
PINNED_TOOLCHAIN = "leanprover/lean4:v4.29.0"
UPSTREAM_PIN = "95a01f598e2cd1cac4052e5e5ff9145c658e18db"
# Paths this project adds (anything else changed vs the pin fails the gate).
_AE = "bench/tritonbench_g/add_example/"
ADDED_PREFIXES = ("VeriTile/Triton/Launch/Blocked1D", "VeriTile/Triton/Launch/Serial.lean",
                  *(_AE + f for f in ("CONTRACT.md", "SOURCE_LINK.md", "HANDOFF.md", "LAUNCH_README.md",
                                      "launch_manifest.json", "launch_evidence/", "improvement/",
                                      ".gitignore")),
                  "bench/tests/Blocked1DLaunchWitnesses.lean",
                  "bench/tritonbench_g/vector_addition_custom/launch_manifest.json",
                  "scripts/launch_", "scripts/test_launch_check.py")
# Upstream registries regenerated by upstream tools and validated in `upstream_static_gates`.
REGISTRIES = ("bench/tritonbench_g/coverage_review.json", "bench/tritonbench_g/proof_gap_manifest.tsv",
              "scripts/kernel-manifest.tsv", "VeriTile/Meta/TrustReport.lean",
              "bench/tritonbench_g/_spec-sheets/")
# Modified upstream Lean files: original code must survive verbatim (additions only).
ADDITIVE = {"VeriTile/Triton/Launch.lean": "prefix",
            "VeriTile/Triton/Launch/Composition.lean": "before-final-end",
            "bench/tritonbench_g/add_example/AddExample.lean": "namespace-body",
            "bench/tritonbench_g/vector_addition_custom/VectorAdditionCustom.lean": "namespace-body"}
# Pinned sources that must be byte-identical to the upstream pin.
PINNED_EXACT = ("bench/tritonbench_g/add_example/add_example.py",
                "bench/tritonbench_g/add_example/README.md",
                "bench/tritonbench_g/vector_addition_custom/vector_addition_custom.py",
                "bench/tritonbench_g/vector_addition_custom/README.md")
PINNED_MATHLIB = "8a178386ffc0f5fef0b77738bb5449d50efeea95"
HEADLINES = ["VeriTile.Bench.TritonBenchG.AddExample.add_kernel_launch_correctness",
             "VeriTile.Bench.TritonBenchG.AddExample.add_kernel_launch_applicable",
             "VeriTile.Bench.TritonBenchG.AddExample.add_kernel_launch_traceSafe",
             "VeriTile.Bench.TritonBenchG.AddExample.add_kernel_correctness",
             "VeriTile.Triton.Blocked1D.launch_of_frames",
             "VeriTile.Triton.Kernel.LaunchCorrectFramed.toLaunchCorrect",
             "VeriTile.Triton.Blocked1DLaunch.check_ok",
             "VeriTile.Triton.Blocked1DLaunch.check_complete",
             "VeriTile.Triton.Blocked1DLaunch.Pre.i32_offset_toInt",
             "VeriTile.Triton.Blocked1DLaunch.Pre.i32_mask_eq",
             "VeriTile.Triton.Blocked1DLaunch.Pre.offset_injective"]

WRAPPER_THEOREMS = [f"VeriTile.Bench.TritonBenchG.AddExample.{t}" for t in (
    "add_wrapper_correctness", "add_kernel_launch_serial", "add_kernel_launch_flat",
    "add_kernel_program_run")] + [f"VeriTile.Triton.{t}" for t in (
    "Kernel.runSerial_agrees_merge", "Blocked1D.launch_of_frames_addr",
    "Elementwise2.check_ok", "Elementwise2.check_complete", "Elementwise2.Pre.output_covered",
    "Elementwise2.Pre.inputs_cover", "Elementwise2.Pre.flat_disjoint",
    "Elementwise2.Pre.windows_in_alloc", "Elementwise2.flatAlloc_closed",
    "TensorMeta.offsetOf_eq_linear", "FlatAlloc.flattenState_withGridIndex")]

AUDIT_TARGETS = [
    ("bench/tritonbench_g/add_example/AddExample.lean", "VeriTile.Bench.TritonBenchG.AddExample",
     HEADLINES + ["VeriTile.Bench.TritonBenchG.AddExample.add_kernel_launch_initial_output_irrelevant"]
     + WRAPPER_THEOREMS,
     ["add_kernel_correctness", "add_kernel_launch_correctness", "add_wrapper_correctness"]),
    ("bench/tritonbench_g/vector_addition_custom/VectorAdditionCustom.lean", VAC,
     [f"{VAC}.add_kernel_correctness", f"{VAC}.add_kernel_launch_correctness",
      f"{VAC}.add_kernel_launch_applicable"],
     ["add_kernel_correctness", "add_kernel_launch_correctness"]),
    ("bench/tests/Blocked1DLaunchWitnesses.lean", WIT,
     [f"{WIT}.{t}" for t in ["testCase1_pre", "emptyCase_pre", "i32_n_truncated", "i32_offset_wraps",
                            "unmasked_store_frame_violation", "offbyone_mask_frame_violation"]], []),
]

# Protected surface: printed from the elaborated environment and compared
# byte-for-byte with the frozen snapshot.
SURFACE_PRINTS = [
    "#print VeriTile.Triton.Kernel.LaunchCorrectFramed",
    "#print VeriTile.Triton.Kernel.LaunchCorrect",
    "#print VeriTile.Triton.Kernel.GridLaunchedOrdinary",
    "#print VeriTile.Triton.Kernel.mergeFrames",
    "#print VeriTile.Triton.Blocked1D.line",
    "#print VeriTile.Triton.Blocked1D.pidOf",
    "#print VeriTile.Triton.Blocked1D.blockWrites",
    "#print VeriTile.Triton.MaskedKernelIO₂.Implements",
    "#print VeriTile.Bench.TritonBenchG.AddExample.add_kernel",
    "#print VeriTile.Bench.TritonBenchG.AddExample.addIO",
] + [f"#check @{h}" for h in HEADLINES] + [
    "#check @VeriTile.Bench.TritonBenchG.AddExample.add_kernel_launch_initial_output_irrelevant"]
VAC_SURFACE_PRINTS = [
    f"#print {VAC}._add_kernel", f"#print {VAC}.addCustomIO",
    f"#check @{VAC}.add_kernel_correctness", f"#check @{VAC}.add_kernel_launch_correctness",
    f"#check @{VAC}.add_kernel_launch_applicable", f"#check @{VAC}.add_kernel_launch_traceSafe",
    f"#check @{VAC}.custom_add_correctness"]
AE_NS = "VeriTile.Bench.TritonBenchG.AddExample"
# Whole-wrapper contract (frozen from its sorry state, stage 5).
WRAPPER_SURFACE_PRINTS = [
    "#print VeriTile.Triton.TensorMeta", "#print VeriTile.Triton.TensorMeta.numel",
    "#print VeriTile.Triton.TensorMeta.rowMajor", "#print VeriTile.Triton.TensorMeta.Contiguous",
    "#print VeriTile.Triton.TensorMeta.offsetOf", "#print VeriTile.Triton.TensorMeta.InShape",
    "#print VeriTile.Triton.TensorMeta.Aligned", "#print VeriTile.Triton.TensorMeta.toBuf",
    "#print VeriTile.Triton.TensorMeta.linear",
    "#print VeriTile.Triton.Elementwise2.launch", "#print VeriTile.Triton.Elementwise2.SameShape",
    "#print VeriTile.Triton.Elementwise2.AllContiguous", "#print VeriTile.Triton.Elementwise2.AllAligned",
    "#print VeriTile.Triton.Elementwise2.InputsSeparate", "#print VeriTile.Triton.Elementwise2.Pre",
    "#print VeriTile.Triton.Elementwise2.OutputCovered", "#print VeriTile.Triton.Elementwise2.InputsCover",
    "#print VeriTile.Triton.Elementwise2.flatAlloc",
    "#check @VeriTile.Triton.Elementwise2.check_ok", "#check @VeriTile.Triton.Elementwise2.check_complete",
    "#check @VeriTile.Triton.Elementwise2.Pre.output_covered",
    "#check @VeriTile.Triton.Elementwise2.Pre.inputs_cover",
    "#check @VeriTile.Triton.Elementwise2.Pre.flat_disjoint",
    "#check @VeriTile.Triton.Elementwise2.Pre.windows_in_alloc",
    "#check @VeriTile.Triton.Elementwise2.flatAlloc_closed",
    "#check @VeriTile.Triton.TensorMeta.offsetOf_eq_linear",
    "#print VeriTile.Triton.Kernel.runSerial", "#print VeriTile.Triton.Kernel.memReal",
    "#print VeriTile.Triton.Kernel.FrameRobust",
    "#check @VeriTile.Triton.Kernel.runSerial_agrees_merge",
    "#print VeriTile.Triton.Blocked1D.addrWrites",
    "#check @VeriTile.Triton.Blocked1D.launch_of_frames_addr",
    f"#check @{AE_NS}.add_wrapper_correctness",
    # stage 5b: dim-0 (rank-1) wrappers
    "#print VeriTile.Triton.Elementwise2.launchDim0", "#print VeriTile.Triton.Elementwise2.Rank1",
    "#check @VeriTile.Triton.Elementwise2.checkRank1_ok",
    "#check @VeriTile.Triton.Elementwise2.checkRank1_complete",
    "#check @VeriTile.Triton.Elementwise2.launchDim0_eq",
    "#check @VeriTile.Triton.Elementwise2.launchDim0_not_covered"]
# (frozen snapshot name, file, prints)
SURFACES = [("launch_surface.txt", "bench/tritonbench_g/add_example/AddExample.lean", SURFACE_PRINTS),
            ("wrapper_surface.txt", "bench/tritonbench_g/add_example/AddExample.lean",
             WRAPPER_SURFACE_PRINTS),
            ("vac_surface.txt", "bench/tritonbench_g/vector_addition_custom/VectorAdditionCustom.lean",
             VAC_SURFACE_PRINTS)]


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def input_hashes(root: Path = REPO) -> dict:
    files = NEW_LEAN + ["VeriTile/Triton/Launch.lean",
                        "bench/tritonbench_g/add_example/add_example.py",
                        "bench/tritonbench_g/add_example/CONTRACT.md",
                        "bench/tritonbench_g/add_example/launch_manifest.json",
                        "bench/tritonbench_g/add_example/improvement/add_example_empty_like.py",
                        "bench/tritonbench_g/add_example/improvement/launch_manifest.json",
                        "bench/tritonbench_g/add_example/improvement/add_example_block64.py",
                        "bench/tritonbench_g/add_example/improvement/launch_manifest_block64.json",
                        "bench/tritonbench_g/vector_addition_custom/vector_addition_custom.py",
                        "bench/tritonbench_g/vector_addition_custom/launch_manifest.json",
                        "scripts/launch_check.py", "scripts/launch_local_check.py",
                        "scripts/launch_emulate.py", "scripts/launch_mutation_suite.py",
                        "scripts/test_launch_check.py",
                        "lean-toolchain", "lake-manifest.json", "lakefile.toml"]
    return {f: sha(root / f) for f in files if (root / f).exists()}


class Step:
    def __init__(self, key, scope, assumptions=""):
        self.key, self.scope, self.assumptions = key, scope, assumptions
        self.status, self.evidence, self.reason, self.detail = "not_run", "", "", {}
        self.t0 = time.time()

    def done(self, status, evidence="", reason="", **detail):
        self.status, self.evidence, self.reason, self.detail = status, evidence, reason, detail
        self.elapsed = round(time.time() - self.t0, 1)
        mark = {"passed": "ok", "failed": "FAIL"}.get(status, status.upper())
        print(f"[{mark}] {self.key}: {reason or evidence}", flush=True)
        return self

    def json(self):
        return {"status": self.status, "scope": self.scope, "assumptions": self.assumptions,
                "evidence": self.evidence, "reason": self.reason,
                "elapsed_s": getattr(self, "elapsed", None), **self.detail}


def run(cmd, cwd, timeout, log: Path | None = None):
    t = time.time()
    try:
        r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout,
                           start_new_session=True)
        out, rc = r.stdout + r.stderr, r.returncode
    except subprocess.TimeoutExpired as e:
        out, rc = f"TIMEOUT after {timeout}s\n{e.stdout or ''}", 124
    if log:
        log.parent.mkdir(parents=True, exist_ok=True)
        log.write_text(f"$ {' '.join(map(str, cmd))}\n# cwd={cwd} rc={rc} "
                       f"elapsed={time.time()-t:.1f}s\n{out}")
    return rc, out


def fresh_workspace(logs: Path) -> Path:
    """Copy tracked + new project sources (no .lake/build) into a temp dir and
    link only the pinned dependency packages, so project modules are rebuilt
    from source rather than trusted from the working tree's build artifacts."""
    ws = Path(tempfile.mkdtemp(prefix="veritile-launch-fresh-"))
    files = subprocess.run(["git", "ls-files", "-co", "--exclude-standard"], cwd=REPO,
                           capture_output=True, text=True, check=True).stdout.split()
    for f in files:
        src = REPO / f
        if src.is_file():
            dst = ws / f
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
    (ws / ".lake").mkdir()
    os.symlink(REPO / ".lake/packages", ws / ".lake/packages")
    return ws


def sequential_build(root: Path, roots: list[str], timeout: int, log: Path):
    """`lake build` one module at a time in import order: Lake 5.0 has no job
    cap, so this bounds concurrency to one Lean process (LEAN_NUM_THREADS=2)."""
    imp = re.compile(r"^\s*(?:public\s+)?import\s+(\S+)", re.M)
    order, seen = [], set()
    def visit(m):
        f = root / (m.replace(".", "/") + ".lean")
        if m in seen or not f.exists():
            return
        seen.add(m)
        for d in imp.findall(f.read_text()):
            if d.startswith("VeriTile"):
                visit(d)
        order.append(m)
    for r in roots:
        visit(r)
    t0, lines = time.time(), []
    for m in order:
        left = timeout - (time.time() - t0)
        if left <= 0:
            lines.append(f"TIMEOUT before {m}")
            rc = 124
            break
        rc, out = run(["lake", "build", m], root, int(left))
        lines.append(f"{m} rc={rc}")
        if rc != 0:
            lines.append(out[-4000:])
            break
    else:
        rc = 0
    log.parent.mkdir(parents=True, exist_ok=True)
    log.write_text(f"# sequential build of {len(order)} modules in {root} "
                   f"({time.time()-t0:.0f}s)\n" + "\n".join(lines) + "\n")
    return rc, "\n".join(lines)


def pin_integrity(root: Path) -> list[str]:
    """Every path differing from the upstream pin is declared; modified upstream
    Lean files keep the pinned code verbatim."""
    git = lambda *a: subprocess.run(["git", *a], cwd=REPO, capture_output=True, text=True).stdout
    changed = {l.split("\t")[-1] for l in git("diff", "--name-status", UPSTREAM_PIN).splitlines() if l}
    changed |= set(git("ls-files", "-o", "--exclude-standard").split())
    problems = []
    for f in sorted(changed):
        if f.startswith(ADDED_PREFIXES) or f.startswith(REGISTRIES) or f in ADDITIVE:
            continue
        problems.append(f"undeclared change: {f}")
    for f in PINNED_EXACT:
        if (root / f).read_bytes() != subprocess.run(["git", "show", f"{UPSTREAM_PIN}:{f}"], cwd=REPO,
                                                     capture_output=True).stdout:
            problems.append(f"pinned source differs from upstream: {f}")
    for f, mode in ADDITIVE.items():
        orig = git("show", f"{UPSTREAM_PIN}:{f}")
        cur = (root / f).read_text()
        if mode == "prefix":
            ok = cur.startswith(orig.rstrip("\n"))
        elif mode == "before-final-end":
            ok = cur.startswith(orig[:orig.rstrip().rindex("end Kernel")])
        else:
            a = orig.index("\nnamespace "); b = orig.rindex("\nend ")
            ok = orig[a:b] in cur
        if not ok:
            problems.append(f"pinned upstream code altered in {f} ({mode})")
    return problems


def placeholder_scan(root: Path) -> list[str]:
    bad = []
    for f in NEW_LEAN:
        code = audit_source.strip_lean_comments((root / f).read_text())
        for m in re.finditer(r"\b(sorry|admit|native_decide|ofReduceBool)\b|^\s*axiom\s", code, re.M):
            bad.append(f"{f}: {m.group(0).strip()}")
    return bad


AUDIT_IMPORT = "import VeriTile.Meta.StatementAudit\n"
MARK = "SURFACE-BEGIN-7f3a"


def audit_file(root: Path, rel: str, ns: str, thms: list[str]) -> str:
    """A Lean file + appended audit commands (a temp copy; the source is untouched)."""
    body = (root / rel).read_text()
    lines = ["", "open VeriTile.Meta"] + [f"#axiomsClean {h}" for h in thms]
    lines += [f"#auditStmt {h}" for h in thms if ".Bench." in h]
    lines += [f"namespace {ns}", "#auditModuleAxioms", f"end {ns}"]
    return AUDIT_IMPORT + body + "\n".join(lines) + "\n"


def surface_file(root: Path, rel: str, prints: list[str]) -> str:
    body = (root / rel).read_text()
    lines = ["", "set_option pp.proofs false", f'#eval IO.println "{MARK}"'] + prints
    return body + "\n".join(lines) + "\n"


def print_surface(root: Path, logs: Path, timeout: int, rel: str, prints: list[str]):
    tmp = (root / rel).parent / ".launch_surface_tmp.lean"
    tmp.write_text(surface_file(root, rel, prints))
    try:
        rc, out = run(["lake", "env", "lean", str(tmp)], root, timeout,
                      logs / f"surface_{Path(rel).stem}.log")
    finally:
        tmp.unlink(missing_ok=True)
    if rc != 0 or MARK not in out:
        return rc or 1, ""
    return rc, out.split(MARK, 1)[1].strip("\n") + "\n"


def external_steps(hashes: dict) -> dict:
    """Official comparator / GPU: evidence files only, never inferred."""
    def external(key, fname, scope):
        st = Step(key, scope)
        f = EVID / fname
        if not f.exists():
            return st.done("not_run", "", f"no {fname}: requires a compatible external environment "
                           f"(see bench/tritonbench_g/add_example/HANDOFF.md)")
        ev = json.loads(f.read_text())
        stale = {k: v for k, v in ev.get("input_hashes", {}).items() if hashes.get(k) != v}
        if stale or not ev.get("input_hashes"):
            return st.done("failed", str(f), f"STALE evidence: {sorted(stale) or 'no hashes'}")
        return st.done("passed" if ev.get("exit_code") == 0 else "failed", str(f),
                       f"exit_code={ev.get('exit_code')}")
    return {
        "official_comparator": external(
            "official_comparator", "official_comparator.json",
            "upstream comparator (Linux, Landlock, systemd) on the changed library + AddExample.lean"),
        "gpu_correctness": external("gpu_correctness", "gpu.json",
                                    "real Triton launch on a supported NVIDIA/AMD GPU"),
        "gpu_performance": external("gpu_performance", "gpu_perf.json",
                                    "steady-state timing on a supported GPU"),
    }


def freeze(a) -> int:
    """Write frozen protected-surface snapshots (all, or only `--freeze-only NAME`).
    Run only on the reviewed statement (sorry) state before proof search, or
    after a recorded review."""
    logs = EVID / "logs"
    FROZEN.mkdir(parents=True, exist_ok=True)
    for name, rel, prints in SURFACES:
        if a.freeze_only and name != a.freeze_only:
            continue
        rc, surface = print_surface(REPO, logs, a.timeout, rel, prints)
        if rc != 0:
            print(f"FREEZE_FAILED {name} rc={rc}")
            return 1
        (FROZEN / name).write_text(surface)
        print(f"FROZEN {name}: {len(surface.splitlines())} lines")
    if not a.freeze_only:
        cfg_rc, cfg_out = run(["lake", "env", "lean", str(FROZEN / "print_config_surface.lean")],
                              REPO, 600)
        if cfg_rc != 0:
            print("FREEZE_FAILED config")
            return 1
        (FROZEN / "config_surface.txt").write_text(cfg_out)
        (FROZEN / "contract.sha256").write_text(sha(KDIR / "CONTRACT.md") + "\n")
    return 0


def external_only(a) -> int:
    steps = external_steps(input_hashes())
    rc = 0
    if a.require_official and steps["official_comparator"].status != "passed":
        print(f"OFFICIAL_AUDIT_REQUIRED_BUT_{steps['official_comparator'].status.upper()}")
        rc = 2
    if a.require_gpu and not all(steps[k].status == "passed"
                                 for k in ("gpu_correctness", "gpu_performance")):
        print("GPU_EVIDENCE_REQUIRED_BUT_MISSING_OR_FAILED")
        rc = rc or 3
    return rc


def main(argv=None) -> int:
    global EVID
    ap = argparse.ArgumentParser()
    ap.add_argument("--fresh", action="store_true",
                    help="rebuild project modules from source in a fresh workspace")
    ap.add_argument("--require-official", action="store_true")
    ap.add_argument("--require-gpu", action="store_true")
    ap.add_argument("--ledger", type=Path, default=EVID / "ledger.json")
    ap.add_argument("--freeze", action="store_true",
                    help="write the frozen surface snapshot (review-gated; records who/why)")
    ap.add_argument("--timeout", type=int, default=1800)
    ap.add_argument("--freeze-only", default=None, help="with --freeze: one snapshot name")
    ap.add_argument("--external-only", action="store_true",
                    help="only evaluate official/GPU evidence against current hashes")
    ap.add_argument("--evidence-dir", type=Path, default=None,
                    help="read external evidence from here (tests)")
    a = ap.parse_args(argv)
    if a.evidence_dir is not None:
        EVID = a.evidence_dir
    env_path = Path.home() / ".elan/bin"
    os.environ["PATH"] = f"{env_path}:{os.environ['PATH']}"
    os.environ.setdefault("LEAN_NUM_THREADS", "2")  # resource cap (see README)
    logs = EVID / "logs"
    steps: dict[str, Step] = {}
    root = REPO

    if a.external_only:
        return external_only(a)
    if a.freeze:
        return freeze(a)

    # L0 pins -------------------------------------------------------------
    s = Step("toolchain_pins", "lean-toolchain, Lean binary, Mathlib revision")
    tc = (REPO / "lean-toolchain").read_text().strip()
    man = json.loads((REPO / "lake-manifest.json").read_text())
    mrev = next(p["rev"] for p in man["packages"] if p["name"] == "mathlib")
    rc, out = run(["lake", "env", "lean", "--version"], REPO, 120)
    ok = tc == PINNED_TOOLCHAIN and mrev == PINNED_MATHLIB and rc == 0 and "4.29.0" in out
    steps[s.key] = s.done("passed" if ok else "failed", out.strip()[:120],
                          "" if ok else f"toolchain={tc} mathlib={mrev} rc={rc}")

    # L1 build ------------------------------------------------------------
    s = Step("build", "project modules rebuilt from source" if a.fresh else
             "lake build in working tree (incremental; use --fresh for final evidence)")
    if a.fresh:
        root = fresh_workspace(logs)
        os.environ["VERITILE_LEAN_ROOT"] = str(root)
    rc, out = sequential_build(root, ["VeriTile.Triton", "VeriTile.Meta.StatementAudit",
                                      "VeriTile.Examples.Common"], a.timeout, logs / "build.log")
    steps[s.key] = s.done("passed" if rc == 0 else "failed", str(logs / "build.log"),
                          f"rc={rc}" + (f" workspace={root}" if a.fresh else ""))

    # L2 placeholder scan ---------------------------------------------------
    s = Step("placeholder_scan", "comment-stripped changed Lean files")
    bad = placeholder_scan(root)
    steps[s.key] = s.done("failed" if bad else "passed", "; ".join(bad) or "none",
                          f"{len(bad)} hits" if bad else "no sorry/admit/native_decide/axiom")

    # L2b upstream pin integrity ----------------------------------------------
    s = Step("upstream_pin_unchanged", f"working tree vs Lizn-zn/VeriTile@{UPSTREAM_PIN[:8]}: only "
             "declared paths change; pinned code in modified Lean files is verbatim")
    probs = pin_integrity(root)
    dirty = subprocess.run(["git", "status", "--porcelain"], cwd=REPO, capture_output=True,
                           text=True).stdout.strip()
    steps[s.key] = s.done("failed" if probs else "passed", "; ".join(probs) or "git diff vs pin",
                          f"{len(probs)} problems" if probs else "no undeclared or non-additive changes",
                          worktree_clean=not dirty)

    # L2c upstream static gates (pure Python/shell; no comparator) -----------
    s = Step("upstream_static_gates", "bench/check_proof_gap_manifest.py; check-artifact.sh's "
             "kernel-manifest validator; committed spec sheets current")
    rc1, o1 = run([sys.executable, "bench/check_proof_gap_manifest.py"], root, 600,
                  logs / "proof_gap_manifest.log")
    fns = re.findall(r"(?ms)^(?:fail|ok|is_comment_or_blank|theorem_exists|valid_manifest_kind|"
                     r"valid_manifest_status|check_kernel_manifest)\(\) \{.*?^\}",
                     (root / "scripts/check-artifact.sh").read_text())
    shfile = logs / "manifest_fns.sh"
    shfile.parent.mkdir(parents=True, exist_ok=True)
    shfile.write_text("\n".join(fns) + "\n")
    rc2, o2 = run(["bash", "-c", f"failures=0; source '{shfile}'; "
                   "KERNEL_MANIFEST=scripts/kernel-manifest.tsv; check_kernel_manifest; "
                   "exit $failures"], root, 600, logs / "kernel_manifest.log")
    rc3, o3 = run([sys.executable, "scripts/spec_sheet.py"], root, 600, logs / "spec_sheet.log")
    if root == REPO:
        sheets = subprocess.run(["git", "status", "--porcelain", "bench/tritonbench_g/_spec-sheets"],
                                cwd=REPO, capture_output=True, text=True).stdout.strip()
    else:  # fresh copy: regenerated sheets must equal the committed ones in the repo
        sd = "bench/tritonbench_g/_spec-sheets"
        sheets = " ".join(sorted(p.name for p in (root / sd).iterdir()
                                 if not (REPO / sd / p.name).exists()
                                 or (REPO / sd / p.name).read_bytes() != p.read_bytes()))
    ok = rc1 == 0 and rc2 == 0 and rc3 == 0 and "self-ref-flagged: 0 | no-summary: 0" in o3 and not sheets
    steps[s.key] = s.done("passed" if ok else "failed", str((logs / "proof_gap_manifest.log").relative_to(REPO)),
                          f"proof-gap rc={rc1}, kernel-manifest rc={rc2}, spec-sheet rc={rc3}"
                          + (f", uncommitted sheet changes: {sheets}" if sheets else ""))

    # L3 kernel files + axioms + inventory ------------------------------
    s = Step("kernel_file_axioms", "AddExample.lean, VectorAdditionCustom.lean, Blocked1DLaunchWitnesses.lean "
             "elaborate; listed theorems' axioms ⊆ {propext, Classical.choice, Quot.sound}; "
             "headline inventory")
    per, all_ok, all_clean = {}, True, []
    for rel, ns, thms, inv_req in AUDIT_TARGETS:
        tmp = (root / rel).parent / ".launch_audit_tmp.lean"
        tmp.write_text(audit_file(root, rel, ns, thms))
        try:
            rc, out = run(["lake", "env", "lean", str(tmp)], root, a.timeout,
                          logs / f"audit_{Path(rel).stem}.log")
        finally:
            tmp.unlink(missing_ok=True)
        clean = sorted(set(re.findall(r"(\S+): axiom footprint ⊆ standard base ✓", out)))
        inv = re.search(r"Axiom audit: headlines=(\d+)\nheadlines: \[(.*?)\]", out, re.S)
        missing = [h for h in thms if h not in clean]
        inv_names = inv.group(2) if inv else ""
        inv_ok = inv is not None and all(
            re.search(rf"\.{re.escape(n)}\b", inv_names) for n in inv_req)
        ok = rc == 0 and not missing and inv_ok
        all_ok &= ok
        all_clean += clean
        surf = {m.group(1): re.sub(r"\s+", " ", m.group(2)).strip() for m in re.finditer(
            r"(\S+) — trusted project surface \(\d+\):\n\[(.*?)\]", out, re.S)}
        per[rel] = {"rc": rc, "missing": missing, "inventory": inv_names, "ok": ok,
                    "statement_surfaces": surf}
    steps[s.key] = s.done("passed" if all_ok else "failed", str(logs / "audit_*.log"),
                          f"{len(AUDIT_TARGETS)} files, axiom-clean {len(set(all_clean))} theorems"
                          + ("" if all_ok else f", problems={ {k: v for k, v in per.items() if not v['ok']} }"),
                          files=per)

    # L4 frozen contract ---------------------------------------------------
    s = Step("frozen_contract", "elaborated protected definitions + headline statements "
             "vs frozen snapshot; CONTRACT.md and checker surface hashes")
    diffs, surfaces = [], {}
    for name, rel, prints in SURFACES:
        srf_rc, surface = print_surface(root, logs, a.timeout, rel, prints)
        surfaces[name] = surface
        if srf_rc != 0 or surface != (FROZEN / name).read_text():
            diffs.append(name)
    cfg_rc, cfg_out = run(["lake", "env", "lean", str(FROZEN / "print_config_surface.lean")],
                          root, 600)
    if cfg_rc != 0 or cfg_out != (FROZEN / "config_surface.txt").read_text():
        diffs.append("config_surface")
    if sha(KDIR / "CONTRACT.md") != (FROZEN / "contract.sha256").read_text().strip():
        diffs.append("CONTRACT.md")
    steps[s.key] = s.done("failed" if diffs else "passed", str(FROZEN),
                          f"CONTRACT_CHANGED: {diffs} (requires recorded review + refreeze)"
                          if diffs else "surface identical to frozen snapshot")
    for name in diffs:
        if name in surfaces:
            (logs / f"{name}.current").write_text(surfaces[name])

    # L5 adapter on manifests -------------------------------------------
    s = Step("source_link_adapter", "actual source + wrapper + Lean transcription + real CPU "
             "tensor metadata -> kernel-checked checker verdicts",
             "adapter recognition and torch metadata are trusted (tested, not proved)")
    results = {}
    manifests = sorted(m for m in REPO.glob("bench/tritonbench_g/**/launch_manifest*.json")
                       if "/." not in str(m.relative_to(REPO)))
    all_ok = True
    for m in manifests:
        try:
            res = launch_check.analyze(m)
            res["status"] = "ok" if all(c["matches_expectation"] for c in res["cases"].values()) \
                else "mismatch"
        except launch_check.Unsupported as e:
            res = {"status": "unsupported", "unsupported": str(e)}
        except Exception as e:  # infrastructure
            res = {"status": "infrastructure_failure", "error": repr(e)}
        results[str(m.relative_to(REPO))] = res
        all_ok &= res["status"] == "ok"
    (EVID / "adapter_results.json").write_text(json.dumps(results, indent=1, sort_keys=True) + "\n")
    n_cases = sum(len(r.get("cases", {})) for r in results.values())
    n_acc = sum(c["accepted"] for r in results.values() for c in r.get("cases", {}).values())
    steps[s.key] = s.done("passed" if all_ok and manifests else "failed",
                          str(EVID / "adapter_results.json"),
                          f"{len(manifests)} manifests, {n_cases} cases, {n_acc} accepted, "
                          f"all verdicts kernel-checked" if all_ok else
                          f"statuses={[r['status'] for r in results.values()]}")

    # L6 adapter unit tests -------------------------------------------------
    s = Step("adapter_tests", "scripts/test_launch_check.py (parser/metadata/Lean-verdict regressions)")
    rc, out = run([sys.executable, "-m", "unittest", "-q", "test_launch_check"],
                  REPO / "scripts", a.timeout, logs / "adapter_tests.log")
    steps[s.key] = s.done("passed" if rc == 0 else "failed", str(logs / "adapter_tests.log"),
                          out.strip().splitlines()[-1] if out.strip() else f"rc={rc}")

    local_ok = all(st.status == "passed" for st in steps.values())
    hashes = input_hashes(root)  # hashes of the copy that was actually verified

    steps.update(external_steps(hashes))

    ledger = {
        "generated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "git_head": subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO, capture_output=True,
                                   text=True).stdout.strip(),
        "input_hashes": hashes,
        "summary": {
            "model_proof": {"status": steps["kernel_file_axioms"].status,
                            "scope": "add_kernel whole-grid launch in VeriTile's exact-ℝ region model",
                            "evidence": steps["kernel_file_axioms"].evidence},
            "checker_soundness": {"status": steps["kernel_file_axioms"].status,
                                  "scope": "check_ok / check_complete / i32 lemmas (Lean)",
                                  "evidence": steps["kernel_file_axioms"].evidence},
            "source_correspondence": {"status": steps["source_link_adapter"].status,
                                      "level": "tested-but-trusted (AST recognizer + statement "
                                               "match); not proved",
                                      "evidence": steps["source_link_adapter"].evidence},
            "local_trust_checks": {"status": "passed" if all(
                steps[k].status == "passed" for k in ("placeholder_scan", "kernel_file_axioms"))
                else "failed", "scope": "placeholder scan, #axiomsClean, headline inventory"},
            "frozen_contract": {"status": steps["frozen_contract"].status,
                                "evidence": steps["frozen_contract"].evidence},
            "official_comparator": steps["official_comparator"].json(),
            "gpu_correctness": steps["gpu_correctness"].json(),
            "gpu_performance": steps["gpu_performance"].json(),
        },
        "steps": {k: v.json() for k, v in steps.items()},
        "fresh_workspace": a.fresh,
    }
    a.ledger.parent.mkdir(parents=True, exist_ok=True)
    ledger["full_library_build"] = {"status": "not_run", "reason": "only the lite subset needed by these "
                                    "files is built (VeriTile.Triton + audit/common modules); default "
                                    "`lake build` / VeriTileFull (TrustReport, ApproxGeLU) not run"}
    ledger["note"] = "adapter_results.json records per-run torch data_ptr bases; they differ run to run"

    def rel(text: str) -> str:
        text = text.replace(str(REPO) + "/", "")
        return text.replace(str(root) + "/", "<fresh-workspace>/") if root != REPO else text
    a.ledger.write_text(rel(json.dumps(ledger, indent=1, ensure_ascii=False)) + "\n")
    if a.fresh and root != REPO:
        ledger["fresh_workspace_matches_repo"] = hashes == input_hashes(REPO)
        a.ledger.write_text(rel(json.dumps(ledger, indent=1, ensure_ascii=False)) + "\n")
        shutil.rmtree(root, ignore_errors=True)

    rc = 0
    if local_ok:
        print("LOCAL_CHECKS_PASSED")
    else:
        print("LOCAL_CHECKS_FAILED")
        rc = 1
    if a.require_official and steps["official_comparator"].status != "passed":
        print(f"OFFICIAL_AUDIT_REQUIRED_BUT_{steps['official_comparator'].status.upper()}")
        rc = rc or 2
    if a.require_gpu and not all(steps[k].status == "passed"
                                 for k in ("gpu_correctness", "gpu_performance")):
        print("GPU_EVIDENCE_REQUIRED_BUT_MISSING_OR_FAILED")
        rc = rc or 3
    return rc


if __name__ == "__main__":
    sys.exit(main())
