#!/usr/bin/env python3
"""Render bench/optimizations/inductor_narrow/CONFIRM.md from launch_evidence/narrow_confirm.json and patch_check.json."""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
EV = REPO / "bench/tritonbench_g/add_example/launch_evidence"
OUT = REPO / "bench/optimizations/inductor_narrow/CONFIRM.md"


def render() -> str:
    c = json.loads((EV / "narrow_confirm.json").read_text())
    p = json.loads((EV / "patch_check.json").read_text())
    a = c["analysis"]
    o = a["overall"]
    L = ["# Stage 14: N1 confirmation and upstream patch check", "",
         "Generated by `scripts/narrow_confirm_report.py` from `launch_evidence/narrow_confirm.json` and",
         "`patch_check.json`. Do not edit by hand. The analysis rules are in `scripts/launch_narrow_confirm.py`,",
         "fixed before the run.", "",
         f"Host: {c['gpu_name']}, torch {c['torch']}, Triton {c['triton']}.",
         f"Design: {a['triples']} paired triples (B0, N, N1), in 2 processes, with Latin-balanced orders and",
         ">= 2 s of sustained warm-up per block. The stopping point was fixed in advance.", "",
         f"## Recommendation (pre-registered): **{a['recommendation']}**", "",
         f"Validity: {a['validity']}", "",
         "| | median | 95% CI (bootstrap over triples) |", "|---|---|---|",
         f"| T(N) / T(N1), complete sequence | {o['median_rT']:.3f} | {o['ci'][0]:.3f} – {o['ci'][1]:.3f} |",
         f"| T(B0) / T(N1) | {o['median_B0_over_N1']:.3f} | {o['ci_B0_over_N1'][0]:.3f} – {o['ci_B0_over_N1'][1]:.3f} |",
         "",
         f"Median T (ms): B0 {o['median_T_ms']['B0']:.1f}, N {o['median_T_ms']['N']:.1f}, N1 {o['median_T_ms']['N1']:.1f}. "
         f"Overall confirmed (median ≥ 1.03 and CI lower bound ≥ 1.00): **{o['confirmed']}**.", "",
         "## Small shapes: absolute µs/call (median over triples) and paired N/N1 ratio", "",
         "| shape | B0 µs | N µs | N1 µs | N/N1 median | 95% CI | class |", "|---|---|---|---|---|---|---|"]
    for k, v in a["small"].items():
        u = v["median_us"]
        L.append(f"| {k} | {u['B0']:.1f} | {u['N']:.1f} | {u['N1']:.1f} | {v['median_rS']:.3f} | "
                 f"{v['ci'][0]:.3f} – {v['ci'][1]:.3f} | {v['class']} |")
    L += ["", f"Median SM clock per variant during measured blocks (MHz): {a.get('clock_median_mhz')}", "",
          "## Upstream patch on the pinned nightly (CUDA), correctness only", "",
          f"- torch {p['torch']}, git `{p['git_version']}`. Pin matches: {p['pin_matches']}. "
          f"Base files match the manifest: {p['base_matches']}.",
          f"- Patch applied: {p['applied']}. Upstream tests rc: {p['upstream_tests_rc']}.",
          f"- 14-shape sequence with the flag on: bitwise equal at every shape: "
          f"{all(p['sequence']['bitwise'].values())}; kernels defined {p['sequence']['kernels_defined']}; "
          f"Dynamo graphs {p['sequence']['unique_graphs']}; ks signature {p['sequence']['ks_signature']}", ""]
    tail = [ln for ln in p["upstream_tests_tail"].splitlines() if ln.startswith("test_") or ln.startswith("Ran") or ln == "OK"]
    L += ["```"] + tail + ["```", ""]
    return "\n".join(L)


if __name__ == "__main__":
    t = render()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == t else 1)
    OUT.write_text(t)
    print("wrote", OUT.relative_to(REPO))
