#!/usr/bin/env python3
"""Render bench/optimizations/inductor_narrow/CONFIRM.md from launch_evidence/narrow_confirm.json and patch_check.json,
and SENSITIVITY.md (non-gating per-process / per-order slices of the same confirmation data; no new measurement)."""
import json
import statistics
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
EV = REPO / "bench/tritonbench_g/add_example/launch_evidence"
OUT = REPO / "bench/optimizations/inductor_narrow/CONFIRM.md"
OUT_SENS = REPO / "bench/optimizations/inductor_narrow/SENSITIVITY.md"


def render() -> str:
    c = json.loads((EV / "narrow_confirm.json").read_text())
    p = json.loads((EV / "patch_check.json").read_text())
    a = c["analysis"]
    o = a["overall"]
    L = ["# Stage 14: N1 confirmation and upstream patch check", "",
         "Generated by `scripts/narrow_confirm_report.py` from `launch_evidence/narrow_confirm.json` and",
         "`patch_check.json`. Do not edit by hand. The analysis rules are in `scripts/launch_narrow_confirm.py`,",
         "fixed before the run.", "",
         f"Host: {c['gpu_name']}, torch {c['torch']}, Triton {c['triton']}.",
         f"Design: {a['triples']} paired triples (B0, N, N1), in 2 processes, with Latin-balanced orders and",
         ">= 2 s of sustained warm-up per block. The stopping point was fixed in advance.", "",
         f"## Recommendation (pre-registered): **{a['recommendation']}**", "",
         f"Validity: {a['validity']}", "",
         "| | median | 95% CI (bootstrap over triples) |", "|---|---|---|",
         f"| T(N) / T(N1), complete sequence | {o['median_rT']:.3f} | {o['ci'][0]:.3f} – {o['ci'][1]:.3f} |",
         f"| T(B0) / T(N1) | {o['median_B0_over_N1']:.3f} | {o['ci_B0_over_N1'][0]:.3f} – {o['ci_B0_over_N1'][1]:.3f} |",
         "",
         f"Median T (ms): B0 {o['median_T_ms']['B0']:.1f}, N {o['median_T_ms']['N']:.1f}, N1 {o['median_T_ms']['N1']:.1f}. "
         f"Overall confirmed (median ≥ 1.03 and CI lower bound ≥ 1.00): **{o['confirmed']}**.", "",
         "## Small shapes: absolute µs/call (median over triples) and paired N/N1 ratio", "",
         "| shape | B0 µs | N µs | N1 µs | N/N1 median | 95% CI | class |", "|---|---|---|---|---|---|---|"]
    for k, v in a["small"].items():
        u = v["median_us"]
        L.append(f"| {k} | {u['B0']:.1f} | {u['N']:.1f} | {u['N1']:.1f} | {v['median_rS']:.3f} | "
                 f"{v['ci'][0]:.3f} – {v['ci'][1]:.3f} | {v['class']} |")
    L += ["", "The µs columns are medians over triples of each variant's time; the N/N1 column is the median over "
          "triples of the paired ratio S_N(t)/S_N1(t), the pre-registered statistic. These are different statistics, "
          "so dividing the displayed medians need not give the paired median (e.g. 3000xodd: 160.8/155.0 ≈ 1.04 "
          "against a paired median of 1.10). Per-process and per-order slices are in SENSITIVITY.md (non-gating). "
          "The CIs describe variability within this experiment only, not across machines, days or compiler revisions."]
    L += ["", f"Median SM clock per variant during measured blocks (MHz): {a.get('clock_median_mhz')}", "",
          "## Upstream patch on the pinned nightly (CUDA), correctness only", "",
          f"- torch {p['torch']}, git `{p['git_version']}`. Pin matches: {p['pin_matches']}. "
          f"Base files match the manifest: {p['base_matches']}.",
          f"- Patch applied: {p['applied']}. Upstream tests rc: {p['upstream_tests_rc']}.",
          f"- 14-shape sequence with the flag on: bitwise equal at every shape: "
          f"{all(p['sequence']['bitwise'].values())}; kernels defined {p['sequence']['kernels_defined']}; "
          f"Dynamo graphs {p['sequence']['unique_graphs']}; ks signature {p['sequence']['ks_signature']}", ""]
    tail = [ln for ln in p["upstream_tests_tail"].splitlines() if ln.startswith("test_") or ln.startswith("Ran") or ln == "OK"]
    L += ["```"] + tail + ["```", ""]
    return "\n".join(L)


def slices(procs: list) -> dict:
    tagged = [(p["proc"], t) for p in procs for t in p["triples"]]
    out = {f"process {i}": [t for p, t in tagged if p == i] for i in sorted({p for p, _ in tagged})}
    out["N before N1"] = [t for _, t in tagged if t["order"].index("N") < t["order"].index("N1")]
    out["N1 before N"] = [t for _, t in tagged if t["order"].index("N1") < t["order"].index("N")]
    for perm in sorted({tuple(t["order"]) for _, t in tagged}):
        out["order " + "-".join(perm)] = [t for _, t in tagged if tuple(t["order"]) == perm]
    out["all"] = [t for _, t in tagged]
    return out


def summ(xs: list) -> str:
    return f"{statistics.median(xs):.3f} [{min(xs):.3f}, {max(xs):.3f}]"


def render_sensitivity() -> str:
    d = json.loads((EV / "narrow_confirm.json").read_text())
    small = [f"{n}x{w}" for n, w in d["small"]]
    sl = slices(d["processes"])
    L = ["# Stage 14 confirmation: sensitivity summaries (non-gating)", "",
         "Generated by `scripts/narrow_confirm_report.py` from `launch_evidence/narrow_confirm.json`. No new "
         "measurement. The pre-registered analysis and recommendation are in CONFIRM.md and are unchanged by this "
         "page. Cells are the median of the paired ratio N/N1 over the slice, with [min, max]; slices hold 4 or 12 "
         "triples, so no confidence intervals are given.", "",
         "These summaries describe variation *within this one experiment* (one L4, one day, one software stack). "
         "They say nothing about variation across machines, GPU families, days, or compiler revisions.", "",
         "## Complete sequence, T(N) / T(N1)", "", "| slice | triples | median [min, max] |", "|---|---|---|"]
    for name, ts in sl.items():
        L.append(f"| {name} | {len(ts)} | {summ([t['blocks']['N']['T_s'] / t['blocks']['N1']['T_s'] for t in ts])} |")
    L += ["", "## Small shapes, S(N) / S(N1), by process and by N/N1 position", ""]
    cols = [k for k in sl if not k.startswith("order ")]
    L += ["| shape | " + " | ".join(cols) + " |", "|---" * (len(cols) + 1) + "|"]
    for s in small:
        L.append(f"| {s} | " + " | ".join(
            summ([t["blocks"]["N"]["small_us"][s] / t["blocks"]["N1"]["small_us"][s] for t in sl[c]]) for c in cols) + " |")
    L += ["", "## Paired-ratio median versus ratio of marginal medians", "",
          "CONFIRM.md reports, per shape, the median over triples of each variant's time and, separately, the median "
          "over triples of the paired ratio S_N(t)/S_N1(t). The second is the pre-registered statistic. The two need "
          "not agree: dividing the displayed medians does not reproduce the paired median.", "",
          "| shape | median S_N µs | median S_N1 µs | ratio of medians | median of paired ratios |", "|---|---|---|---|---|"]
    ts = sl["all"]
    for s in small:
        mn = statistics.median(t["blocks"]["N"]["small_us"][s] for t in ts)
        m1 = statistics.median(t["blocks"]["N1"]["small_us"][s] for t in ts)
        pr = statistics.median(t["blocks"]["N"]["small_us"][s] / t["blocks"]["N1"]["small_us"][s] for t in ts)
        L.append(f"| {s} | {mn:.1f} | {m1:.1f} | {mn / m1:.3f} | {pr:.3f} |")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    pages = {OUT: render(), OUT_SENS: render_sensitivity()}
    if "--check" in sys.argv:
        sys.exit(0 if all(o.exists() and o.read_text() == t for o, t in pages.items()) else 1)
    for o, t in pages.items():
        o.write_text(t)
        print("wrote", o.relative_to(REPO))
